[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tibec"
version = "0.1.0"
description = "Time Integrated Beam pattern in Equatorial Coordinates"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
authors = [
    {name = "Zheng Zhang"},
]

dependencies = [
    "numpy",
    "scipy",
    "healpy",
    "matplotlib",
]

[tool.setuptools.packages.find]
include = ["tibec*"]

[project.optional-dependencies]
dev = [
    "jupyter",
    "pytest",
]
